name: Build project and upload to Appcenter

on: [push, pull_request]

jobs:
  buildForAndroidPlatform:
    name: Build for Android
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          lfs: true
          submodules: recursive
      - uses: game-ci/unity-builder@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          targetPlatform: Android
          androidAppBundle: false
          androidKeystoreName: user.keystore
          androidKeystoreBase64: ${{ secrets.ANDROID_KEYSTORE_BASE64 }}
          androidKeystorePass: ${{ secrets.ANDROID_KEYSTORE_PASS }}
          androidKeyaliasName: ${{ secrets.ANDROID_KEYALIAS_NAME }}
          androidKeyaliasPass: ${{ secrets.ANDROID_KEYALIAS_PASS }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-Android
          path: build/Android
         
  releaseToAppcenter:
    name: upload artefact to App Center
    runs-on: ubuntu-latest
    needs: buildForAndroidPlatform
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Download Android Artifact
        uses: actions/download-artifact@v2
        with:
          name: build-Android
          path: build/Android
      - uses: wzieba/AppCenter-Github-Action@v1
        with:
          appName: gsunyercaldu-gmail.com/Playground
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Collaborators
          file: ${{ format('{0}/build/Android/Android.apk', github.workspace) }}
          notifyTesters: true
          debug: false
  cleanup:
    name: Cleanup to avoid storage limit
    runs-on: ubuntu-latest
    if: always()
    steps:
      - name: Cleanup
        uses: geekyeggo/delete-artifact@v1
        with:
          name: build-Android
          

